#ifndef OBSCURE_GLFW_VULKAN_INCLUDES
#define OBSCURE_GLFW_VULKAN_INCLUDES 1

#define VK_USE_PLATFORM_WIN32_KHR
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#define GLFW_EXPOSE_NATIVE_WIN32
#include <GLFW/glfw3native.h>
#endif